import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistAlomani = localFont({
  src: "./fonts/AlomaniByCattobiens-Regular.woff",
  variable: "--font-AlomaniByCattobiens-Regular",
  weight: "100 900",
});

export const metadata = {
  title: "Tyara Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistAlomani.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
